# Site settings
title: Fortress of Solitude
email: goel.aviral@gmail.com
description: "Aviral's Fortress of Solitude"
baseurl: ""
url: "http://aviral.io"

# Build settings
markdown: kramdown
permalink: pretty
