project:
  type: website
  resources:
    - "static"

website:
  title: "Aviral Goel"
  site-url: http://aviral.io
  navbar:
    left:
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/aviralg
      - icon: linkedin
        href: https://www.linkedin.com/in/aviralgoel
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree
  open-graph:
    locale: en_US
    site-name: Aviral Goel

format:
  html:
    theme:
      - litera
    css: styles.css
    toc: true

language:
  search-text-placeholder: Search

