project:
  type: website

website:
  title: "Aviral Goel"
  navbar:
    #background: primary
    left:
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/aviralg
  search:
    location: navbar
    type: textbox
    copy-button: true
    show-item-context: tree
  open-graph:
    locale: en_US
    site-name: Aviral Goel

format:
  html:
    theme:
      - simplex
    css: styles.css
    toc: true

language:
  search-text-placeholder: Search

