project:
  type: website
  resources:
    - "static"

website:
  title: Aviral Goel
  site-url: http://aviral.io
  description: Aviral Goel's Website
  favicon: logo.png
  navbar:
    title: false
    collapse: false
    left:
      - href: blog.qmd
        text: BLOG
    right:
      - icon: envelope
        href: mailto:goel.aviral@gmail.com
        aria-label: Email
      - icon: github
        href: https://github.com/aviralg
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/aviralgoel
        aria-label: Linkedin
      - icon: rss
        href: blog.xml
        aria-label: RSS
  search: false
  open-graph:
    locale: en_US
    site-name: Aviral Goel

format:
  html:
    theme:
      - theme.scss
    toc: true
    code-fold: true
    highlight-style: printing
    code-line-numbers: true
    code-link: true
