# Created 2021-10-08 Fri 09:18
#+TITLE: Example Org File
#+DATE: 2020-10-27
#+AUTHOR: TEC
#+startup: latexpreview

* Revamp orgmode.org website
The /beauty/ of org *must* be shared.
[[https://upload.wikimedia.org/wikipedia/commons/b/bd/Share_Icon.svg]]

** DONE Make screenshots

** DONE Restyle Site CSS

Go through [[file:style.scss][stylesheet]]

** TODO Check CSS on main pages

* Learn Org

Org makes easy things trivial and complex things practical.

You don't need to learn Org before using Org: read the quickstart
page and you should be good to go.  If you need more, Org will be
here for you as well: dive into the manual and join the community!

** Feedback

* Check CSS minification ratios

#+begin_src python
  from pathlib import Path
  cssRatios = []
  for css_min in Path("resources/style").glob("*.min.css"):
      css = css_min.with_suffix('').with_suffix('.css')
      cssRatios.append([css.name,
      "{:.0f}% minified ({:4.1f} KiB)".format( 100 *
                        css_min.stat().st_size / css.stat().st_size,
                        css_min.stat().st_size / 1000)])
  return cssRatios
#+end_src

Evaluated results
#+results: 
| index.css    | 76% minified ( 1.4 KiB) |
| org-demo.css | 77% minified ( 2.8 KiB) |
| errors.css   | 74% minified ( 4.9 KiB) |
| org.css      | 75% minified (10.7 KiB) |

#+begin_src latex
  \setlength{\unitlength}{1cm}
  \thicklines
  \begin{picture}(10,6)
  \put(2,2.2){\line(1,0){6}}
  \put(2,2.2){\circle{2}}
  \put(6,2.2){\oval(4,2)[r]}
  \end{picture}
#+end_src


\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures
\end{equation}                          % etc

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].
